import { Recipe } from '../types/recipe';

export const RECIPES_DATABASE: Recipe[] = [
  {
    id: 'r-carbonara',
    title: 'Pravé krémové špagety Carbonara',
    description: 'Tradiční římská klasika se žloutky, křupavou slaninou a parmazánem bez kapky smetany.',
    category: 'obed_vece',
    prepTime: 20,
    difficulty: 'Střední',
    portions: 2,
    calories: 540,
    macros: { protein: 26, carbs: 58, fat: 22 },
    tags: ['Italská kuchyně', 'Rychlovka', 'Vysoký protein'],
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Špagety', amount: '220 g', numericValue: 220, unit: 'g' },
      { name: 'Vejce', amount: '3 ks žloutků + 1 celé', numericValue: 4, unit: 'ks' },
      { name: 'Parmazán', amount: '60 g', numericValue: 60, unit: 'g' },
      { name: 'Slanina', amount: '120 g', numericValue: 120, unit: 'g' },
      { name: 'Černý pepř', amount: '1 lžička', numericValue: 1, unit: 'lžička' },
    ],
    instructions: [
      'Dejte vařit vydatně osolenou vodu na špagety a uvařte je al dente.',
      'Na pánvi na mírném ohni pomalu opečte nakrájenou slaninu dokřupava.',
      'V misce prošlehejte žloutky, jedno celé vejce, najemno nastrouhaný parmazán a čerstvě drcený černý pepř.',
      'Uvařené špagety přendejte kleštěmi rovnou k orestované slanině (mimo oheň!).',
      'Přidejte cca 3 lžíce horké vody z těstovin a vlijte vaječnou směs.',
      'Rychle míchejte, dokud teplo těstovin nevytvoří lesklou, sametovou omáčku. Nikdy nevracejte na prudký oheň, aby se vejce nesrazila.',
    ],
    chefTip: 'Voda ze špaget plná škrobu je tajemstvím dokonalé emulze. Přilévejte ji po lžících, dokud omáčka není dokonale hedvábná.',
  },
  {
    id: 'r-shakshuka',
    title: 'Orientální Shakshuka s vejci a rajčaty',
    description: 'Bohatá jednopánvová snídaně či večeře s voňavou rajčatovou omáčkou a tekutými žloutky.',
    category: 'snidane',
    prepTime: 25,
    difficulty: 'Snadné',
    portions: 2,
    calories: 320,
    macros: { protein: 18, carbs: 22, fat: 16 },
    tags: ['Vegetariánské', 'Jedna pánev', 'Bez lepku'],
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Vejce', amount: '4 ks', numericValue: 4, unit: 'ks' },
      { name: 'Rajčata', amount: '4 ks zralých nebo plechovka drcených', numericValue: 4, unit: 'ks' },
      { name: 'Cibule', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Paprika', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Olivový olej', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
      { name: 'Chilli vločky', amount: '1 špetka', numericValue: 1, unit: 'špetka', optional: true },
    ],
    instructions: [
      'Na olivovém oleji na pánvi zesklovatějte jemně nakrájenou cibuli s paprikou na nudličky.',
      'Přidejte nasekaný česnek a po minutě vsypte nakrájená rajčata.',
      'Osolte, opepřete a nechte omáčku zhruba 10 minut probublávat a zhoustnout.',
      'V omáčce vařečkou vytvořte 4 důlky a do každého opatrně vyklepněte jedno vejce.',
      'Pánev přiklopte pokličkou a nechte na mírném plamenu 5-7 minut, dokud bílky neztuhnou, ale žloutky zůstanou tekuté.',
      'Podávejte s čerstvým pečivem.',
    ],
    chefTip: 'Na závěr můžete posypat rozdrobenou fetou nebo čerstvou petrželkou.',
  },
  {
    id: 'r-omeleta-spenat',
    title: 'Nadýchaná francouzská omeleta se špenátem a sýrem',
    description: 'Jemná máslová omeleta s čerstvým listovým špenátem a rozteklým sýrem do 10 minut.',
    category: 'snidane',
    prepTime: 12,
    difficulty: 'Snadné',
    portions: 1,
    calories: 360,
    macros: { protein: 24, carbs: 4, fat: 28 },
    tags: ['Rychlovka', 'Nízkosacharidové', 'Vegetariánské'],
    imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Vejce', amount: '3 ks', numericValue: 3, unit: 'ks' },
      { name: 'Baby špenát', amount: '50 g', numericValue: 50, unit: 'g' },
      { name: 'Máslo', amount: '20 g', numericValue: 20, unit: 'g' },
      { name: 'Parmazán', amount: '30 g (nebo čedar)', numericValue: 30, unit: 'g' },
      { name: 'Česnek', amount: '1 stroužek', numericValue: 1, unit: 'stroužek', optional: true },
    ],
    instructions: [
      'Na pánvi rozpusťte kousek másla a nechte špenát cca 1 minutu zavadnout s nasekaným česnekem. Vyjměte stranou.',
      'Vejce vidličkou jemně prošlehejte se špetkou soli a pepře (nepřešlehávejte).',
      'Na čisté pánvi rozpusťte zbytek másla na středním plamenu.',
      'Vlijte vejce a neustále míchejte vidličkou krouživým pohybem cca 40 vteřin pro jemnou krémovou texturu.',
      'Když je spodek lehce zpevněný a vrch krémový, poklaďte špenátem a nastrouhaným sýrem.',
      'Omeletu přeložte napůl a sesypte na talíř.',
    ],
    chefTip: 'Tajemstvím je nevysušit vnitřek – pravá omeleta musí být uvnitř ještě lehce vláčná a lesklá.',
  },
  {
    id: 'r-kureci-brambory',
    title: 'Šťavnatá kuřecí prsa na bylinkovém másle s pečenými bramborami',
    description: 'Dokonale zlatavé kuřecí maso provoněné česnekem a rozmarýnem s křupavými brambůrkami.',
    category: 'obed_vece',
    prepTime: 35,
    difficulty: 'Střední',
    portions: 2,
    calories: 520,
    macros: { protein: 48, carbs: 42, fat: 16 },
    tags: ['Vysoký protein', 'Česká klasika', 'Syté jídlo'],
    imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Kuřecí prsa', amount: '450 g', numericValue: 450, unit: 'g' },
      { name: 'Brambory', amount: '500 g', numericValue: 500, unit: 'g' },
      { name: 'Máslo', amount: '35 g', numericValue: 35, unit: 'g' },
      { name: 'Česnek', amount: '3 stroužky', numericValue: 3, unit: 'stroužky' },
      { name: 'Olivový olej', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
    ],
    instructions: [
      'Brambory omyjte, nakrájejte na měsíčky, promíchejte s lžící olivového oleje, solí a dejte péct na 200 °C na 25 minut dozlatova.',
      'Kuřecí prsa podélně rozkrojte na tenčí plátky, osolte a opepřete.',
      'Na pánvi rozpalte zbylý olej a zprudka opečte kuře 3 minuty z každé strany.',
      'Ztlumte oheň, přidejte máslo a rozmáčknutý česnek. Lžící přelévejte pěnící máslo přes maso po dobu 2 minut.',
      'Nechte maso 3 minuty odpočinout na prkénku a servírujte s křupavými bramborami.',
    ],
    chefTip: 'Přelévání horkým pěnícím máslem (tzv. arosování) zaručí, že kuřecí prsa zůstanou neuvěřitelně šťavnatá.',
  },
  {
    id: 'r-bramboraky',
    title: 'Křupavé české bramboráčky s majoránkou a česnekem',
    description: 'Tradiční křupavé placičky ze strouhaných brambor s poctivou dávkou česneku a vůní majoránky.',
    category: 'obed_vece',
    prepTime: 30,
    difficulty: 'Snadné',
    portions: 2,
    calories: 390,
    macros: { protein: 11, carbs: 54, fat: 15 },
    tags: ['Česká klasika', 'Vegetariánské', 'Levné a chutné'],
    imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Brambory', amount: '600 g', numericValue: 600, unit: 'g' },
      { name: 'Vejce', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Česnek', amount: '4 stroužky', numericValue: 4, unit: 'stroužky' },
      { name: 'Hladká mouka', amount: '3 lžíce', numericValue: 3, unit: 'lžíce' },
      { name: 'Sušená majoránka', amount: '1 lžíce', numericValue: 1, unit: 'lžíce' },
      { name: 'Olivový olej', amount: 'na smažení', numericValue: 3, unit: 'lžíce' },
    ],
    instructions: [
      'Brambory oloupejte a nastrouhejte najemno. Důkladně z nich rukama nebo přes utěrku vymačkejte přebytečnou vodu.',
      'Přidejte vejce, prolisovaný česnek, mouku, sůl a majoránku promnutou mezi dlaněmi.',
      'Vše spojte v těsto.',
      'Na pánvi rozpalte olej a lžící tvořte tenké placičky.',
      'Smažte z obou stran dozlatova a dokřupava (cca 3 minuty z každé strany).',
      'Odsajte přebytečný tuk na papírové utěrce a ihned podávejte.',
    ],
    chefTip: 'Čím důkladněji vymačkáte z brambor škrobovou vodu, tím křupavější bramboráky budou.',
  },
  {
    id: 'r-aglio-olio',
    title: 'Těstoviny Aglio, Olio e Peperoncino',
    description: 'Rychlá a geniálně jednoduchá italská večeře z těstovin, česneku a kvalitního olivového oleje.',
    category: 'obed_vece',
    prepTime: 15,
    difficulty: 'Snadné',
    portions: 2,
    calories: 460,
    macros: { protein: 14, carbs: 68, fat: 16 },
    tags: ['Rychlovka', 'Vegetariánské', 'Italská kuchyně'],
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Špagety', amount: '240 g', numericValue: 240, unit: 'g' },
      { name: 'Česnek', amount: '5 stroužků', numericValue: 5, unit: 'stroužků' },
      { name: 'Olivový olej', amount: '5 lžic extra panenského', numericValue: 5, unit: 'lžic' },
      { name: 'Chilli vločky', amount: '1/2 lžičky', numericValue: 0.5, unit: 'lžičky' },
      { name: 'Parmazán', amount: '40 g', numericValue: 40, unit: 'g', optional: true },
    ],
    instructions: [
      'Špagety dejte vařit do vroucí osolené vody.',
      'Česnek nakrájejte na velmi tenké plátky.',
      'Na studenou pánev nalijte olivový olej, přidejte česnek a chilli a zahřívejte na mírném ohni, aby česnek zesklovatěl a zezlátnul, ale nespálil se.',
      'Špagety sceďte a trochu vody z hrnce uschovejte.',
      'Vhoďte těstoviny do pánve k česneku, přilijte 3 lžíce vody z těstovin a energicky promíchejte.',
      'Posypejte čerstvým parmazánem a podávejte horké.',
    ],
    chefTip: 'Česnek nesmí zhnědnout, jinak zhořkne. Zahřívejte ho pomalu od studeného oleje.',
  },
  {
    id: 'r-stir-fry',
    title: 'Kuřecí Stir-Fry se zeleninou a rýží',
    description: 'Barevná a svěží asijská pánev s křehkým kuřecím masem, zeleninou a lesklou omáčkou.',
    category: 'obed_vece',
    prepTime: 20,
    difficulty: 'Snadné',
    portions: 2,
    calories: 480,
    macros: { protein: 42, carbs: 54, fat: 10 },
    tags: ['Vysoký protein', 'Rychlovka', 'Asijská kuchyně'],
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Kuřecí prsa', amount: '400 g', numericValue: 400, unit: 'g' },
      { name: 'Rýže basmati', amount: '180 g', numericValue: 180, unit: 'g' },
      { name: 'Paprika', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Mrkev', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Cibule', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Sójová omáčka', amount: '3 lžíce', numericValue: 3, unit: 'lžíce' },
      { name: 'Olivový olej', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
    ],
    instructions: [
      'Uvařte rýži v osolené vodě doměkka.',
      'Kuřecí maso i zeleninu nakrájejte na tenké proužky.',
      'Na pánvi Wok nebo hluboké pánvi zprudka orestujte na lžíci oleje kuřecí maso (cca 4 minuty) a dejte stranou.',
      'Do stejné pánve přidejte zeleninu a nasekaný česnek a restujte zprudka 3 minuty, aby zůstala křupavá.',
      'Vraťte maso, zalijte sójovou omáčkou a lžící vody, promíchejte a nechte 1 minutu projít varem.',
      'Podávejte na nadýchané rýži.',
    ],
    chefTip: 'Klíčem k dokonalému stir-fry je vysoká teplota pánve a krátká doba přípravy zeleniny.',
  },
  {
    id: 'r-rajcatova-polevka',
    title: 'Krémová pečená rajčatová polévka s mozzarellou',
    description: 'Hustá sametová polévka ze zralých rajčat s pečeným česnekem a rozteklou mozzarellou.',
    category: 'obed_vece',
    prepTime: 30,
    difficulty: 'Snadné',
    portions: 2,
    calories: 310,
    macros: { protein: 14, carbs: 24, fat: 18 },
    tags: ['Vegetariánské', 'Polévka', 'Pohodové jídlo'],
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Rajčata', amount: '6 ks větších zralých', numericValue: 6, unit: 'ks' },
      { name: 'Cibule', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Česnek', amount: '3 stroužky', numericValue: 3, unit: 'stroužky' },
      { name: 'Olivový olej', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
      { name: 'Mozzarella', amount: '125 g', numericValue: 125, unit: 'g' },
      { name: 'Máslo', amount: '15 g', numericValue: 15, unit: 'g', optional: true },
    ],
    instructions: [
      'Na lžíci olivového oleje a másla orestujte nasekanou cibuli dosklovata.',
      'Přidejte nasekaný česnek a na kousky nakrájená rajčata.',
      'Osolte, opepřete a nechte pod pokličkou dusit 15-20 minut, dokud rajčata zcela nezměknou.',
      'Polévku rozmixujte ponorným mixérem dohladka (můžete zjemnit kapkou smetany či lžící másla).',
      'Nalijte do misek a navrch položte plátky mozzarelly, které se v horké polévce lahodně roztečou.',
    ],
    chefTip: 'Pokud jsou rajčata málo sladká, přidejte špetku medu nebo cukru pro vyvážení kyselosti.',
  },
  {
    id: 'r-zapecene-brambory',
    title: 'Gratinované francouzské brambory se smetanou a sýrem',
    description: 'Zlatavé plátky brambor zapečené ve smetanové lázni s česnekem a sýrovou kůrčičkou.',
    category: 'obed_vece',
    prepTime: 45,
    difficulty: 'Snadné',
    portions: 3,
    calories: 490,
    macros: { protein: 15, carbs: 46, fat: 28 },
    tags: ['Zapečené', 'Vegetariánské', 'Rodinný oběd'],
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Brambory', amount: '800 g', numericValue: 800, unit: 'g' },
      { name: 'Smetana', amount: '250 ml', numericValue: 250, unit: 'ml' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Máslo', amount: '20 g na vymazání', numericValue: 20, unit: 'g' },
      { name: 'Parmazán', amount: '60 g (nebo čedar)', numericValue: 60, unit: 'g' },
    ],
    instructions: [
      'Brambory oloupejte a nakrájejte na tenké plátky (cca 3 mm).',
      'Zapékací mísu vymažte máslem a vytřete rozkrojeným stroužkem česneku.',
      'Brambory navrstvěte do mísy, každou vrstvu lehce osolte, opepřete.',
      'Smetanu promíchejte s prolisovaným česnekem a přelijte přes brambory.',
      'Posypejte nastrouhaným sýrem a pečte při 180 °C cca 40 minut, dokud nejsou brambory měkké a povrch zlatavý.',
    ],
    chefTip: 'Plátky brambor po nakrájení neomývejte – přirozený škrob pomůže zahustit smetanovou omáčku.',
  },
  {
    id: 'r-livance',
    title: 'Nadýchané ovesné lívance s medem a jablky',
    description: 'Zdravé, voňavé snídaňové lívanečky z ovesných vloček hotové za 15 minut.',
    category: 'snidane',
    prepTime: 15,
    difficulty: 'Snadné',
    portions: 2,
    calories: 340,
    macros: { protein: 16, carbs: 48, fat: 9 },
    tags: ['Snídaně', 'Zdravé', 'Sladké'],
    imageUrl: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Ovesné vločky', amount: '120 g', numericValue: 120, unit: 'g' },
      { name: 'Vejce', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Mléko', amount: '100 ml', numericValue: 100, unit: 'ml' },
      { name: 'Jablka', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Máslo', amount: '15 g na opékání', numericValue: 15, unit: 'g' },
      { name: 'Kvalitní med', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
    ],
    instructions: [
      'Vločky, vejce a mléko rozmixujte v mixéru na hladké polotekuté těstíčko.',
      'Jablko oloupejte a nakrájejte na tenké plátky nebo nastrouhejte nahrubo a vmíchejte do těsta.',
      'Na pánvi rozpusťte trochu másla a lžící tvořte menší lívanečky.',
      'Smažte na středním plamenu cca 2 minuty z každé strany dozlatova.',
      'Podávejte pokapané medem.',
    ],
    chefTip: 'Pár kapek citronové šťávy a špetka skořice pozvednou chuť jablek na novou úroveň.',
  },
  {
    id: 'r-tunak-salat',
    title: 'Svěží proteinový salát s tuňákem a vejcem',
    description: 'Bleskový vyvážený oběd plný bílkovin s vařeným vejcem, zeleninou a citronovou zálivkou.',
    category: 'obed_vece',
    prepTime: 12,
    difficulty: 'Snadné',
    portions: 1,
    calories: 380,
    macros: { protein: 34, carbs: 12, fat: 20 },
    tags: ['Vysoký protein', 'Rychlovka', 'Bez lepku'],
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Tuňák v konzervě', amount: '1 plechovka (160 g)', numericValue: 160, unit: 'g' },
      { name: 'Vejce', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Rajčata', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Cibule', amount: '1/2 ks červené', numericValue: 0.5, unit: 'ks' },
      { name: 'Olivový olej', amount: '1 lžíce', numericValue: 1, unit: 'lžíce' },
      { name: 'Citron', amount: '1/2 ks šťáva', numericValue: 0.5, unit: 'ks' },
    ],
    instructions: [
      'Vejce uvařte natvrdo nebo nahniličko (cca 7 minut), ochlaďte a oloupejte.',
      'Rajčata nakrájejte na měsíčky a cibuli na tenká půlkolečka.',
      'V míse smíchejte okapaného tuňáka, rajčata a cibuli.',
      'Zalijte zálivkou z olivového oleje, citronové šťávy, soli a čerstvého pepře.',
      'Doplňte rozkrojenými vejci a ihned podávejte.',
    ],
    chefTip: 'Pokud máte v lednici zbytek těstovin nebo fazolí, vmíchejte je pro ještě sytější verzi.',
  },
  {
    id: 'r-losos-maslo',
    title: 'Pečený filet z lososa na másle s brokolicí a citronem',
    description: 'Šťavnatý losos s křupavou kůžičkou, podávaný s dušenou brokolicí na másle.',
    category: 'obed_vece',
    prepTime: 18,
    difficulty: 'Snadné',
    portions: 2,
    calories: 460,
    macros: { protein: 38, carbs: 8, fat: 31 },
    tags: ['Zdravé tuky', 'Vysoký protein', 'Keto přívětivé'],
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Filet z lososa', amount: '350 g', numericValue: 350, unit: 'g' },
      { name: 'Brokolice', amount: '300 g', numericValue: 300, unit: 'g' },
      { name: 'Máslo', amount: '30 g', numericValue: 30, unit: 'g' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Citron', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Olivový olej', amount: '1 lžíce', numericValue: 1, unit: 'lžíce' },
    ],
    instructions: [
      'Brokolici rozeberte na růžičky a povařte ve vroucí osolené vodě 3 minuty, poté zchlaďte ve studené vodě.',
      'Lososa osolte, opepřete a pokapejte citronem.',
      'Na pánvi rozpalte olej a lososa opečte kůží dolů 4 minuty, poté otočte na 2 minuty.',
      'Přidejte máslo a nasekaný česnek a přelijte pěnícím máslem lososa i okapanou brokolici.',
      'Podávejte s klínky čerstvého citronu.',
    ],
    chefTip: 'Lososa nikdy nepropékejte příliš dlouho – uvnitř by měl zůstat lehce růžový a maximálně šťavnatý.',
  },
  {
    id: 'r-vajecna-pomazanka',
    title: 'Poctivá vajíčková pomazánka s máslem a cibulkou',
    description: 'Klasická krémová pomazánka ze svařených vajec, jemného másla a špetky hořčice.',
    category: 'svacina',
    prepTime: 15,
    difficulty: 'Snadné',
    portions: 2,
    calories: 280,
    macros: { protein: 14, carbs: 3, fat: 24 },
    tags: ['Česká klasika', 'Svačina', 'Rychlovka'],
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Vejce', amount: '4 ks', numericValue: 4, unit: 'ks' },
      { name: 'Máslo', amount: '50 g změklého', numericValue: 50, unit: 'g' },
      { name: 'Plnotučná hořčice', amount: '1 lžička', numericValue: 1, unit: 'lžička' },
      { name: 'Cibule', amount: '1/2 ks malé', numericValue: 0.5, unit: 'ks' },
    ],
    instructions: [
      'Vejce uvařte natvrdo (9 minut), zchlaďte ledovou vodou a oloupejte.',
      'Žloutky vyjměte a v misce utřete se změklým máslem a hořčicí dohladka.',
      'Bílky a cibuli nakrájejte najemno.',
      'Vše spojte, dochuťte solí a čerstvě mletým pepřem.',
      'Mažte na čerstvý chléb nebo bagetku.',
    ],
    chefTip: 'Pro ještě jemnější pomazánku přidejte lžíci bílého jogurtu nebo kapku smetany.',
  },
  {
    id: 'r-cockova-polevka',
    title: 'Rychlá polévka z červené čočky a mrkve',
    description: 'Hřejivá, výživná polévka hotová za 20 minut bez nutnosti namáčení luštěnin.',
    category: 'obed_vece',
    prepTime: 20,
    difficulty: 'Snadné',
    portions: 2,
    calories: 310,
    macros: { protein: 18, carbs: 46, fat: 6 },
    tags: ['Vegetariánské', 'Vysoký obsah vlákniny', 'Levné a chutné'],
    imageUrl: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Červená čočka', amount: '160 g', numericValue: 160, unit: 'g' },
      { name: 'Mrkev', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Cibule', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Olivový olej', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
      { name: 'Sušená majoránka', amount: '1 lžička', numericValue: 1, unit: 'lžička', optional: true },
    ],
    instructions: [
      'Na oleji v hrnci orestujte nakrájenou cibuli a mrkev na kolečka.',
      'Přidejte česnek a propláchnutou červenou čočku.',
      'Zalijte cca 700 ml vody nebo vývaru, osolte a vařte 15 minut do změknutí.',
      'Část polévky můžete rozmixovat pro krémovější konzistenci.',
      'Dochuťte majoránkou a podávejte.',
    ],
    chefTip: 'Červená čočka se uvaří bleskově a krásně přirozeně polévku zahustí bez jíšky.',
  },
  {
    id: 'r-quesadilla',
    title: 'Křupavá sýrová quesadilla se šunkou a rajčaty',
    description: 'Oblíbená mexická placka plněná rozteklým sýrem, šunkou a šťavnatými rajčaty.',
    category: 'svacina',
    prepTime: 12,
    difficulty: 'Snadné',
    portions: 1,
    calories: 420,
    macros: { protein: 26, carbs: 32, fat: 21 },
    tags: ['Rychlovka', 'Svačina', 'Dětský favorit'],
    imageUrl: 'https://images.unsplash.com/photo-1618040996337-56904b7850b9?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Tortilly', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Čedar', amount: '80 g (nebo mozzarella)', numericValue: 80, unit: 'g' },
      { name: 'Dušená šunka', amount: '60 g', numericValue: 60, unit: 'g' },
      { name: 'Rajčata', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Máslo', amount: '10 g na pánev', numericValue: 10, unit: 'g' },
    ],
    instructions: [
      'Na suchou nebo lehce máslem potřenou pánev položte jednu tortillu.',
      'Posypte polovinou sýra, poklaďte plátky šunky a tenkými plátky rajčat.',
      'Zasypte zbytkem sýra a přiklopte druhou tortillou.',
      'Opékejte na středním ohni cca 3 minuty dozlatova, pak opatrně obraťte a opečte druhou stranu.',
      'Nakrájejte na trojúhelníčky a podávejte.',
    ],
    chefTip: 'Sýr dejte dospod i nahoru – funguje jako spolehlivé lepidlo, které udrží placku pohromadě.',
  },
  {
    id: 'r-rizoto-houby',
    title: 'Krémové houbové rizoto s máslem a parmazánem',
    description: 'Pravé italské risotto mantecato s restovanými žampiony a hedvábnou parmazánovou texturou.',
    category: 'obed_vece',
    prepTime: 30,
    difficulty: 'Střední',
    portions: 2,
    calories: 470,
    macros: { protein: 14, carbs: 64, fat: 18 },
    tags: ['Italská kuchyně', 'Vegetariánské', 'Krémové'],
    imageUrl: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Rýže basmati', amount: '180 g (ideálně arborio)', numericValue: 180, unit: 'g' },
      { name: 'Žampiony', amount: '200 g', numericValue: 200, unit: 'g' },
      { name: 'Máslo', amount: '40 g', numericValue: 40, unit: 'g' },
      { name: 'Cibule', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Parmazán', amount: '50 g', numericValue: 50, unit: 'g' },
      { name: 'Olivový olej', amount: '1 lžíce', numericValue: 1, unit: 'lžíce' },
    ],
    instructions: [
      'Na oleji a kousku másla opečte na plátky nakrájené houby dozlatova a vyjměte stranou.',
      'Ve stejném hrnci zesklovatějte jemně nasekanou cibuli a česnek.',
      'Přisypte suchou rýži a minutu ji restujte, až zprůsvitní.',
      'Postupně po naběračkách přilévejte horkou osolenou vodu nebo vývar a míchejte, dokud se tekutina nevsákne.',
      'Po cca 18 minutách, kdy je rýže al dente, stáhněte z ohně, vmíchejte houby, studené kostičky másla a nastrouhaný parmazán.',
      'Přiklopte na 2 minuty pokličkou, energicky promíchejte a ihned servírujte.',
    ],
    chefTip: 'Vynechání ohně při závěrečném vmíchání studeného másla (mantecatura) vytvoří dokonalou krémovost.',
  },
  {
    id: 'r-kure-na-paprice',
    title: 'Tradiční kuře na paprice se smetanou a těstovinami',
    description: 'Oblíbená česká klasika se sametovou smetanovou omáčkou a šťavnatým kuřecím masem.',
    category: 'obed_vece',
    prepTime: 35,
    difficulty: 'Snadné',
    portions: 2,
    calories: 560,
    macros: { protein: 44, carbs: 48, fat: 22 },
    tags: ['Česká klasika', 'Vysoký protein', 'Rodinný oběd'],
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Kuřecí prsa', amount: '450 g', numericValue: 450, unit: 'g' },
      { name: 'Smetana', amount: '200 ml', numericValue: 200, unit: 'ml' },
      { name: 'Cibule', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Máslo', amount: '30 g', numericValue: 30, unit: 'g' },
      { name: 'Špagety', amount: '200 g (nebo kolínka)', numericValue: 200, unit: 'g' },
      { name: 'Paprika', amount: '2 lžičky mleté sladké', numericValue: 2, unit: 'lžičky' },
    ],
    instructions: [
      'Na másle orestujte nadrobno nakrájenou cibulku dosklovata.',
      'Přisypte mletou papriku, krátce (cca 20 vteřin) promíchejte a ihned vložte na kousky nakrájené kuřecí maso.',
      'Maso opečte, osolte, opepřete a zalijte trochou vody či vývaru.',
      'Duste pod pokličkou 15 minut, dokud maso nezměkne.',
      'Přilijte smetanu a nechte omáčku mírně zhoustnout (případně můžete rozmixovat cibuli tyčovým mixérem pro extra hladkost).',
      'Podávejte s uvařenými těstovinami.',
    ],
    chefTip: 'Papriku restujte na mírném ohni a jen krátce, aby nezhořkla.',
  },
  {
    id: 'r-gnocchi-spenat',
    title: 'Krémové noky se špenátem, smetanou a parmazánem',
    description: 'Bleskový vegetariánský oběd hotový do 15 minut plný smetanové chuti a čerstvého špenátu.',
    category: 'obed_vece',
    prepTime: 15,
    difficulty: 'Snadné',
    portions: 2,
    calories: 490,
    macros: { protein: 16, carbs: 62, fat: 20 },
    tags: ['Rychlovka', 'Vegetariánské', 'Italská kuchyně'],
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Těstoviny penne', amount: '300 g (nebo gnocchi)', numericValue: 300, unit: 'g' },
      { name: 'Baby špenát', amount: '120 g', numericValue: 120, unit: 'g' },
      { name: 'Smetana', amount: '180 ml', numericValue: 180, unit: 'ml' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Parmazán', amount: '40 g', numericValue: 40, unit: 'g' },
      { name: 'Máslo', amount: '20 g', numericValue: 20, unit: 'g' },
    ],
    instructions: [
      'Těstoviny či noky uvařte v osolené vroucí vodě podle návodu.',
      'Na pánvi rozpusťte máslo a krátce orestujte nasekaný česnek.',
      'Přidejte baby špenát a nechte ho 1 minutu zavadnout.',
      'Vlijte smetanu, osolte, opepřete a nechte omáčku 2 minuty zredukovat.',
      'Vmíchejte horké noky a nastrouhaný parmazán, který omáčku krásně zahustí.',
      'Ihned servírujte s čerstvě mletým pepřem.',
    ],
    chefTip: 'Pro ještě bohatší chuť můžete na závěr přihodit kousek gorgonzoly nebo mozzarelly.',
  },
  {
    id: 'r-bramboracka',
    title: 'Poctivá česká bramboračka s houbami a česnekem',
    description: 'Hustá polévka vonící po lesních houbách a majoránce, která zahřeje v chladných dnech.',
    category: 'obed_vece',
    prepTime: 35,
    difficulty: 'Snadné',
    portions: 3,
    calories: 270,
    macros: { protein: 8, carbs: 42, fat: 8 },
    tags: ['Česká klasika', 'Polévka', 'Vegetariánské'],
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Brambory', amount: '450 g', numericValue: 450, unit: 'g' },
      { name: 'Mrkev', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Žampiony', amount: '150 g', numericValue: 150, unit: 'g' },
      { name: 'Cibule', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Česnek', amount: '3 stroužky', numericValue: 3, unit: 'stroužky' },
      { name: 'Sušená majoránka', amount: '1 lžíce', numericValue: 1, unit: 'lžíce' },
      { name: 'Máslo', amount: '25 g', numericValue: 25, unit: 'g' },
    ],
    instructions: [
      'Na másle v hrnci orestujte nakrájenou cibuli, na kostičky pokrájenou mrkev a houby.',
      'Přidejte oloupané a na kostky nakrájené brambory.',
      'Zalijte cca 1 litrem vody, osolte, opepřete a vařte 15–20 minut do změknutí brambor.',
      'Do horké polévky prolisujte česnek a přidejte vydatnou dávku v dlaních promnuté majoránky.',
      'Pár kostek brambor rozmačkejte vidličkou pro přirozené zahuštění polévky bez mouky.',
      'Odstavte a nechte 5 minut odstát, aby se rozvinula chuť bylinek.',
    ],
    chefTip: 'Majoránku přidávejte až úplně na konci a nevařte ji, zachová si tak intenzivní vůni.',
  },
  {
    id: 'r-bolognese',
    title: 'Poctivé boloňské špagety s mletým hovězím masem',
    description: 'Hustá masová omáčka pomalu tažená na rajčatech s kořenovou zeleninou a parmazánem.',
    category: 'obed_vece',
    prepTime: 40,
    difficulty: 'Střední',
    portions: 2,
    calories: 590,
    macros: { protein: 38, carbs: 64, fat: 20 },
    tags: ['Vysoký protein', 'Italská kuchyně', 'Rodinný oběd'],
    imageUrl: 'https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Mleté hovězí maso', amount: '350 g', numericValue: 350, unit: 'g' },
      { name: 'Špagety', amount: '220 g', numericValue: 220, unit: 'g' },
      { name: 'Rajčata', amount: '4 ks (nebo rajčatový protlak)', numericValue: 4, unit: 'ks' },
      { name: 'Cibule', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Mrkev', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Olivový olej', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
      { name: 'Parmazán', amount: '40 g', numericValue: 40, unit: 'g' },
    ],
    instructions: [
      'Na olivovém oleji orestujte nadrobno nakrájenou cibuli, mrkev a česnek.',
      'Přidejte mleté hovězí maso a vařečkou ho rozmělněte na menší kousky, dokud nezhnědne.',
      'Osolte, opepřete a přidejte pokrájená rajčata s trochou vody.',
      'Ztlumte plamen a nechte omáčku pozvolna bublat cca 25 minut, aby maso změklo a chutě se propojily.',
      'Špagety uvařte al dente a promíchejte přímo s částí omáčky.',
      'Podávejte posypané strouhaným parmazánem.',
    ],
    chefTip: 'Jemně nakrájená mrkev dodá omáčce přirozenou sladkost bez nutnosti přidávat cukr.',
  },
  {
    id: 'r-chilli-con-carne',
    title: 'Hovězí chilli con carne s rýží a paprikou',
    description: 'Pikantní a voňavý mexický pokrm z mletého masa, šťavnatých rajčat a rýže.',
    category: 'obed_vece',
    prepTime: 35,
    difficulty: 'Snadné',
    portions: 2,
    calories: 520,
    macros: { protein: 36, carbs: 56, fat: 16 },
    tags: ['Pikantní', 'Vysoký protein', 'Jedna pánev'],
    imageUrl: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Mleté hovězí maso', amount: '350 g', numericValue: 350, unit: 'g' },
      { name: 'Rýže basmati', amount: '180 g', numericValue: 180, unit: 'g' },
      { name: 'Rajčata', amount: '3 ks', numericValue: 3, unit: 'ks' },
      { name: 'Paprika', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Cibule', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Chilli vločky', amount: '1/2 lžičky', numericValue: 0.5, unit: 'lžičky' },
      { name: 'Olivový olej', amount: '1 lžíce', numericValue: 1, unit: 'lžíce' },
    ],
    instructions: [
      'Rýži uvařte v osolené vodě doměkka.',
      'V hluboké pánvi na oleji orestujte nakrájenou cibuli, papriku a mleté maso.',
      'Přidejte česnek, chilli, osolte, opepřete a vmíchejte rajčata.',
      'Přiklopte a duste 20 minut, dokud omáčka nezhoustne.',
      'Podávejte s kopečkem rýže.',
    ],
    chefTip: 'Čtvereček hořké čokolády přidaný do omáčky prohloubí její barvu i chuť.',
  },
  {
    id: 'r-kureci-rizky',
    title: 'Křupavé kuřecí řízečky s máslovou bramborovou kaší',
    description: 'Zlatavý rodinný evergreen – šťavnaté kuřecí řízky a hedvábná kaše s mlékem a máslem.',
    category: 'obed_vece',
    prepTime: 35,
    difficulty: 'Střední',
    portions: 2,
    calories: 580,
    macros: { protein: 46, carbs: 52, fat: 22 },
    tags: ['Česká klasika', 'Vysoký protein', 'Dětský favorit'],
    imageUrl: 'https://images.unsplash.com/photo-1599921841143-819065a55cc6?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Kuřecí prsa', amount: '450 g', numericValue: 450, unit: 'g' },
      { name: 'Brambory', amount: '600 g', numericValue: 600, unit: 'g' },
      { name: 'Vejce', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Hladká mouka', amount: '4 lžíce', numericValue: 4, unit: 'lžíce' },
      { name: 'Máslo', amount: '40 g', numericValue: 40, unit: 'g' },
      { name: 'Mléko', amount: '100 ml', numericValue: 100, unit: 'ml' },
    ],
    instructions: [
      'Brambory oloupejte, nakrájejte a uvařte v osolené vodě doměkka.',
      'Kuřecí prsa nakrájejte na plátky, lehce naklepejte, osolte a opepřete.',
      'Obalte je v mouce, rozšlehaných vejcích a opečte na pánvi dozlatova (cca 4 minuty z každé strany).',
      'Uvařené brambory sceďte, přidejte teplé mléko, máslo a vyšlehejte do hladké kaše.',
      'Podávejte s plátkem citronu.',
    ],
    chefTip: 'Do rozšlehaných vajec přidejte lžíci mléka pro ještě křehčí obal.',
  },
  {
    id: 'r-sunkofleky',
    title: 'Zapečené šunkofleky se smetanou a vajíčkem',
    description: 'Tradiční zapečené těstoviny s kousky kvalitní šunky a zlatavou kůrčičkou.',
    category: 'obed_vece',
    prepTime: 35,
    difficulty: 'Snadné',
    portions: 3,
    calories: 460,
    macros: { protein: 24, carbs: 54, fat: 16 },
    tags: ['Česká klasika', 'Zapečené', 'Rychlovka'],
    imageUrl: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Těstoviny penne', amount: '300 g (nebo fleky)', numericValue: 300, unit: 'g' },
      { name: 'Dušená šunka', amount: '200 g', numericValue: 200, unit: 'g' },
      { name: 'Vejce', amount: '3 ks', numericValue: 3, unit: 'ks' },
      { name: 'Smetana', amount: '150 ml (nebo mléko)', numericValue: 150, unit: 'ml' },
      { name: 'Máslo', amount: '25 g na vymazání', numericValue: 25, unit: 'g' },
      { name: 'Parmazán', amount: '40 g', numericValue: 40, unit: 'g', optional: true },
    ],
    instructions: [
      'Těstoviny uvařte al dente v osolené vodě a sceďte.',
      'Šunku nakrájejte na kostičky a promíchejte s těstovinami.',
      'V misce prošlehejte vejce se smetanou, solí a pepřem.',
      'Zapékací mísu vymažte máslem, vsypte těstoviny a zalijte vaječnou směsí.',
      'Pečte v troubě vyhřáté na 190 °C cca 25 minut dozlatova.',
      'Podávejte s kyselou okurkou.',
    ],
    chefTip: 'Před zapečením můžete šunku krátce opéct na másle s cibulkou pro ještě výraznější aroma.',
  },
  {
    id: 'r-palacinky',
    title: 'Jemné tenké palačinky s jablky a medem',
    description: 'Klasické nadýchané palačinky z mléka a vajec s plátky jablek dušených na másle s medem.',
    category: 'dezert',
    prepTime: 20,
    difficulty: 'Snadné',
    portions: 2,
    calories: 360,
    macros: { protein: 12, carbs: 54, fat: 11 },
    tags: ['Sladké', 'Snídaně', 'Dětský favorit'],
    imageUrl: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Mléko', amount: '350 ml', numericValue: 350, unit: 'ml' },
      { name: 'Hladká mouka', amount: '150 g', numericValue: 150, unit: 'g' },
      { name: 'Vejce', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Máslo', amount: '20 g', numericValue: 20, unit: 'g' },
      { name: 'Jablka', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Kvalitní med', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
    ],
    instructions: [
      'V míse vyšlehejte mléko, vejce, špetku soli a mouku na hladké tekuté těsto. Nechte 5 minut odpočinout.',
      'Jablka nakrájejte na tenké plátky a poduste je 3 minuty na pánvi na trošce másla a medu.',
      'Na rozpálené pánvi lehce potřené máslem smažte tenké palačinky z obou stran dozlatova.',
      'Palačinky naplňte teplými medovými jablky, zarolujte a podávejte.',
    ],
    chefTip: 'Přidáním lžíce rozpuštěného másla přímo do těsta zajistíte, že se palačinky nebudou lepit k pánvi.',
  },
  {
    id: 'r-caesar-salad',
    title: 'Svěží Caesar salát s kuřecím masem a parmazánem',
    description: 'Křupavý salát se šťavnatým kuřecím masem, hoblinkami parmazánu a citronovou zálivkou.',
    category: 'obed_vece',
    prepTime: 20,
    difficulty: 'Snadné',
    portions: 2,
    calories: 420,
    macros: { protein: 40, carbs: 14, fat: 22 },
    tags: ['Vysoký protein', 'Rychlovka', 'Nízkosacharidové'],
    imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Kuřecí prsa', amount: '400 g', numericValue: 400, unit: 'g' },
      { name: 'Parmazán', amount: '50 g', numericValue: 50, unit: 'g' },
      { name: 'Vejce', amount: '2 ks vařená', numericValue: 2, unit: 'ks' },
      { name: 'Česnek', amount: '1 stroužek', numericValue: 1, unit: 'stroužek' },
      { name: 'Citron', amount: '1/2 ks šťáva', numericValue: 0.5, unit: 'ks' },
      { name: 'Olivový olej', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
    ],
    instructions: [
      'Kuřecí prsa osolte, opepřete a opečte na lžíci olivového oleje zprudka z obou stran (cca 4 minuty z každé strany).',
      'Vejce uvařte nahniličko (6 minut) a rozkrojte.',
      'Připravte zálivku: promíchejte olivový olej, citronovou šťávu, prolisovaný česnek, sůl a pepř.',
      'Kuřecí maso nakrájejte na plátky, doplňte vejci, parmazánem a přelijte zálivkou.',
    ],
    chefTip: 'Hoblinky parmazánu snadno vytvoříte běžnou škrabkou na brambory.',
  },
  {
    id: 'r-losos-teriyaki',
    title: 'Glazovaný losos v medovo-sójové omáčce s rýží',
    description: 'Šťavnatý rybí filet v lesklé asijské redukci se sladkým medem, česnekem a dušenou rýží.',
    category: 'obed_vece',
    prepTime: 20,
    difficulty: 'Snadné',
    portions: 2,
    calories: 490,
    macros: { protein: 36, carbs: 50, fat: 16 },
    tags: ['Asijská kuchyně', 'Zdravé tuky', 'Vysoký protein'],
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Filet z lososa', amount: '350 g', numericValue: 350, unit: 'g' },
      { name: 'Rýže basmati', amount: '180 g', numericValue: 180, unit: 'g' },
      { name: 'Sójová omáčka', amount: '3 lžíce', numericValue: 3, unit: 'lžíce' },
      { name: 'Kvalitní med', amount: '1.5 lžíce', numericValue: 1.5, unit: 'lžíce' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Máslo', amount: '15 g', numericValue: 15, unit: 'g' },
    ],
    instructions: [
      'Uvařte rýži ve vroucí osolené vodě doměkka.',
      'V mističce promíchejte sójovou omáčku, med a prolisovaný česnek.',
      'Na pánvi rozpalte kousek másla a lososa opečte kůží dolů 3 minuty.',
      'Otočte a vlijte připravenou medovo-sójovou omáčku.',
      'Na mírném plamenu vařte cca 2 minuty, dokud omáčka nezhoustne na lesklou glazuru a neobalí rybu.',
      'Podávejte s horkou rýží a přelijte zbylou omáčkou z pánve.',
    ],
    chefTip: 'Lososa opékejte jen do chvíle, kdy se omáčka začne lepit, aby med nezhořkl.',
  },
  {
    id: 'r-kvetakove-placky',
    title: 'Křupavé brokolicové placičky se sýrem čedar',
    description: 'Voňavé pečené placičky z jemně nasekané brokolice se sýrem a česnekem.',
    category: 'obed_vece',
    prepTime: 25,
    difficulty: 'Snadné',
    portions: 2,
    calories: 330,
    macros: { protein: 20, carbs: 18, fat: 20 },
    tags: ['Vegetariánské', 'Nízkosacharidové', 'Bez masa'],
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Brokolice', amount: '350 g', numericValue: 350, unit: 'g' },
      { name: 'Čedar', amount: '100 g', numericValue: 100, unit: 'g' },
      { name: 'Vejce', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Hladká mouka', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
      { name: 'Olivový olej', amount: '2 lžíce na smažení', numericValue: 2, unit: 'lžíce' },
    ],
    instructions: [
      'Brokolici povařte 3 minuty ve vroucí vodě, sceďte a nasekejte najemno.',
      'V míse smíchejte brokolici s vejci, nastrouhaným čedarem, moukou a česnekem.',
      'Osolte, opepřete a lžící tvořte na pánvi s olejem placičky.',
      'Opékejte z obou stran dozlatova cca 3–4 minuty.',
      'Podávejte samotné nebo s bílým jogurtem a bylinkami.',
    ],
    chefTip: 'Brokolici po uvaření důkladně osušte utěrkou, aby těsto nebylo příliš vodnaté.',
  },
  {
    id: 'r-zapeceny-wrap',
    title: 'Křupavý zapečený wrap s kuřecím masem a mozzarellou',
    description: 'Teplá křupavá tortilla plněná kousky orestovaného kuřete, rajčaty a rozteklým sýrem.',
    category: 'svacina',
    prepTime: 15,
    difficulty: 'Snadné',
    portions: 1,
    calories: 450,
    macros: { protein: 38, carbs: 36, fat: 16 },
    tags: ['Rychlovka', 'Vysoký protein', 'Svačina'],
    imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Tortilly', amount: '1 ks velké', numericValue: 1, unit: 'ks' },
      { name: 'Kuřecí prsa', amount: '150 g', numericValue: 150, unit: 'g' },
      { name: 'Mozzarella', amount: '80 g', numericValue: 80, unit: 'g' },
      { name: 'Rajčata', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Olivový olej', amount: '1 lžíce', numericValue: 1, unit: 'lžíce' },
    ],
    instructions: [
      'Kuřecí maso nakrájejte na tenké nudličky, osolte a opečte na pánvi 4 minuty dozlatova.',
      'Tortillu položte na suchou pánev nebo prkénko.',
      'Doprostřed naskládejte maso, plátky rajčat a natrhanou mozzarellu.',
      'Tortillu pevně zabalte a opečte na suché pánvi z obou stran 2 minuty dokřupava.',
      'Rozkrojte šikmo napůl a podávejte ještě horké.',
    ],
    chefTip: 'Zabalení je nejjednodušší: nejprve přeložte spodní a horní okraj, pak pevně srolujte ze strany.',
  },
  {
    id: 'r-penne-quattro-formaggi',
    title: 'Krémové penne se sýrovou omáčkou z čedaru a parmazánu',
    description: 'Horké těstoviny obalené v hedvábné sýrovo-smetanové omáčce s čerstvě mletým pepřem.',
    category: 'obed_vece',
    prepTime: 15,
    difficulty: 'Snadné',
    portions: 2,
    calories: 540,
    macros: { protein: 22, carbs: 58, fat: 24 },
    tags: ['Rychlovka', 'Vegetariánské', 'Italská kuchyně'],
    imageUrl: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Těstoviny penne', amount: '220 g', numericValue: 220, unit: 'g' },
      { name: 'Smetana', amount: '180 ml', numericValue: 180, unit: 'ml' },
      { name: 'Čedar', amount: '70 g', numericValue: 70, unit: 'g' },
      { name: 'Parmazán', amount: '40 g', numericValue: 40, unit: 'g' },
      { name: 'Máslo', amount: '20 g', numericValue: 20, unit: 'g' },
      { name: 'Černý pepř', amount: '1/2 lžičky', numericValue: 0.5, unit: 'lžičky' },
    ],
    instructions: [
      'Penne uvařte v osolené vroucí vodě al dente.',
      'V pánvi rozpusťte máslo a vlijte smetanu na mírný oheň.',
      'Za stálého míchání přidejte nastrouhaný čedar i parmazán, dokud se zcela nerozpustí.',
      'Přidejte scezené těstoviny přímo do omáčky a promíchejte.',
      'Opepřete a podávejte ihned, dokud se sýr táhne.',
    ],
    chefTip: 'Pokud je omáčka příliš hustá, stačí přilít 2 lžíce horké vody ze slitých těstovin.',
  },
  {
    id: 'r-krupicova-kase',
    title: 'Tradiční jemná krupicová kaše s máslem a skořicí',
    description: 'Nostalgická sladká večeře či snídaně provoněná máslem, jablky a medem.',
    category: 'dezert',
    prepTime: 10,
    difficulty: 'Snadné',
    portions: 2,
    calories: 340,
    macros: { protein: 11, carbs: 56, fat: 9 },
    tags: ['Sladké', 'Snídaně', 'Rychlovka'],
    imageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Mléko', amount: '500 ml', numericValue: 500, unit: 'ml' },
      { name: 'Hladká mouka', amount: '60 g (nebo krupice)', numericValue: 60, unit: 'g' },
      { name: 'Máslo', amount: '30 g rozpuštěného', numericValue: 30, unit: 'g' },
      { name: 'Kvalitní med', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
      { name: 'Jablka', amount: '1 ks', numericValue: 1, unit: 'ks', optional: true },
    ],
    instructions: [
      'V rendlíku přiveďte mléko k varu se špetkou soli.',
      'Za stálého šlehání metličkou pomalu přisypávejte mouku nebo krupici.',
      'Vařte na mírném ohni za stálého míchání cca 3 minuty do zhoustnutí.',
      'Nalijte do hlubokých talířů a bohatě polijte rozpuštěným máslem a medem.',
      'Doplňte plátky jablek a podávejte teplé.',
    ],
    chefTip: 'Šlehání metličkou od samého začátku zajistí, že v kaši nevzniknou žádné hrudky.',
  },
  {
    id: 'r-minestrone',
    title: 'Hustá italská polévka Minestrone se zeleninou a těstovinami',
    description: 'Výživná barevná zeleninová polévka se špagetami, rajčaty, mrkví a parmazánem.',
    category: 'obed_vece',
    prepTime: 30,
    difficulty: 'Snadné',
    portions: 3,
    calories: 290,
    macros: { protein: 10, carbs: 46, fat: 7 },
    tags: ['Vegetariánské', 'Polévka', 'Vysoký obsah vlákniny'],
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Špagety', amount: '100 g nalámaných', numericValue: 100, unit: 'g' },
      { name: 'Rajčata', amount: '3 ks', numericValue: 3, unit: 'ks' },
      { name: 'Mrkev', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Brambory', amount: '250 g', numericValue: 250, unit: 'g' },
      { name: 'Cibule', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Česnek', amount: '2 stroužky', numericValue: 2, unit: 'stroužky' },
      { name: 'Olivový olej', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
      { name: 'Parmazán', amount: '30 g na posyp', numericValue: 30, unit: 'g', optional: true },
    ],
    instructions: [
      'Na olivovém oleji orestujte nakrájenou cibuli, mrkev a česnek.',
      'Přidejte brambory na kostičky a nakrájená rajčata.',
      'Zalijte vodou nebo vývarem, osolte a vařte 15 minut.',
      'Přidejte nalámané špagety a vařte dalších 8 minut do změknutí.',
      'Dochuťte solí a bylinkami a na talíři posypte strouhaným parmazánem.',
    ],
    chefTip: 'Využijte jakoukoliv zbylou zeleninu z lednice – cuketa, pórek i fazolky se do polévky skvěle hodí.',
  },
  {
    id: 'r-cizrnova-cockova-panev',
    title: 'Aromatická červená čočka na rajčatech s česnekem a rýží',
    description: 'Hřejivé indicky laděné kari z červené čočky, rajčat a voňavého česneku servírované s rýží.',
    category: 'obed_vece',
    prepTime: 25,
    difficulty: 'Snadné',
    portions: 2,
    calories: 410,
    macros: { protein: 20, carbs: 68, fat: 6 },
    tags: ['Vegetariánské', 'Vysoký protein', 'Levné a chutné'],
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Červená čočka', amount: '160 g', numericValue: 160, unit: 'g' },
      { name: 'Rýže basmati', amount: '180 g', numericValue: 180, unit: 'g' },
      { name: 'Rajčata', amount: '3 ks', numericValue: 3, unit: 'ks' },
      { name: 'Cibule', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Česnek', amount: '3 stroužky', numericValue: 3, unit: 'stroužky' },
      { name: 'Olivový olej', amount: '2 lžíce', numericValue: 2, unit: 'lžíce' },
      { name: 'Chilli vločky', amount: '1 špetka', numericValue: 1, unit: 'špetka', optional: true },
    ],
    instructions: [
      'Rýži uvařte v osolené vodě doměkka.',
      'Na oleji v pánvi opečte cibuli s česnekem dosklovata.',
      'Přidejte nasekaná rajčata, chilli a propláchnutou červenou čočku.',
      'Podlijte 300 ml vody a duste pod pokličkou 15 minut, dokud čočka nezměkne na krémovou směs.',
      'Osolte dle chuti a podávejte s nadýchanou rýží.',
    ],
    chefTip: 'Červená čočka se nemusí předem namáčet a vytvoří sametovou texturu bez kapky smetany.',
  },
  {
    id: 'r-kureci-jogurt-salat',
    title: 'Lehký kuřecí salát s bylinkovým jogurtem a jablky',
    description: 'Osvěžující a křupavý salát s trhaným kuřecím masem, plátky sladkých jablek a jogurtem.',
    category: 'obed_vece',
    prepTime: 15,
    difficulty: 'Snadné',
    portions: 2,
    calories: 340,
    macros: { protein: 38, carbs: 18, fat: 12 },
    tags: ['Vysoký protein', 'Rychlovka', 'Lehké jídlo'],
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Kuřecí prsa', amount: '350 g', numericValue: 350, unit: 'g' },
      { name: 'Bílý jogurt', amount: '150 g', numericValue: 150, unit: 'g' },
      { name: 'Jablka', amount: '1 ks', numericValue: 1, unit: 'ks' },
      { name: 'Citron', amount: '1/2 ks šťáva', numericValue: 0.5, unit: 'ks' },
      { name: 'Olivový olej', amount: '1 lžíce', numericValue: 1, unit: 'lžíce' },
      { name: 'Plnotučná hořčice', amount: '1 lžička', numericValue: 1, unit: 'lžička' },
    ],
    instructions: [
      'Kuřecí prsa opečte na pánvi z obou stran doměkka (cca 8 minut), nechte zchladnout a natrhejte nebo nakrájejte na sousta.',
      'Jablko nakrájejte na tenké plátky a pokapejte citronem, aby nezhnědlo.',
      'V misce rozmíchejte bílý jogurt s hořčicí, solí a pepřem.',
      'Smíchejte kuřecí maso s jablky a jogurtovým dresinkem.',
      'Podávejte s čerstvým pečivem nebo jen tak jako lehkou večeři.',
    ],
    chefTip: 'Kombinace šťavnatého jablka a jemného jogurtu dodá salátu nezaměnitelnou svěžest.',
  },
  {
    id: 'r-avocado-egg-toast',
    title: 'Křupavý toust se sázeným vejcem a rajčátky',
    description: 'Stylová kavárenská snídaně s křupavým pečivem, tekutým žloutkem a čerstvými rajčaty.',
    category: 'snidane',
    prepTime: 10,
    difficulty: 'Snadné',
    portions: 1,
    calories: 290,
    macros: { protein: 14, carbs: 22, fat: 16 },
    tags: ['Snídaně', 'Rychlovka', 'Vegetariánské'],
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      { name: 'Vejce', amount: '2 ks', numericValue: 2, unit: 'ks' },
      { name: 'Rajčata', amount: '1 ks (nebo cherry)', numericValue: 1, unit: 'ks' },
      { name: 'Tortilly', amount: '1 ks (nebo plátek chleba)', numericValue: 1, unit: 'ks' },
      { name: 'Máslo', amount: '15 g', numericValue: 15, unit: 'g' },
      { name: 'Olivový olej', amount: '1 lžička', numericValue: 1, unit: 'lžička' },
    ],
    instructions: [
      'Na suché pánvi opečte tortillu nebo chléb dokřupava.',
      'Na pánvi rozpusťte kousek másla a připravte sázená vejce na mírném ohni, aby žloutek zůstal krásně tekutý.',
      'Rajčata nakrájejte na plátky a položte na teplé křupavé pečivo.',
      'Navrch položte horká vejce, osolte mořskou solí, opepřete a zakápněte olivovým olejem.',
    ],
    chefTip: 'Pánev při pečení vajec na chvilku přiklopte pokličkou – horní bílek se zatáhne bez nutnosti otáčení.',
  },
];
